// web/src/views/TrainingCockpit.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import ArchitectureCard from '../components/ArchitectureCard.vue'
import HyperparameterCard from '../components/HyperparameterCard.vue'
import TwoStageControlCard from '../components/TwoStageControlCard.vue'
import HardwareEstimatorCard from '../components/HardwareEstimatorCard.vue'
import { launchTrainingJobAPI } from '../api/client'
import type { DatasetInfo } from '../types/dataset'

const props = defineProps<{ datasets?: DatasetInfo[] }>()
const emit = defineEmits<{ (e: 'jobLaunched', result: any): void }>()

const family = ref('yolo26')
const scale = ref('s')
const task = ref('detect')
const selectedDataset = ref(props.datasets?.[0]?.id || '')
const isLaunching = ref(false)
const errorMsg = ref('')
const params = ref({
  epochs: 50, batch: 16, imgsz: 640, optimizer: 'AdamW', lr0: 0.001, amp: true,
  workers: 8, patience: 20, close_mosaic: 10, two_stage: false,
  stage1_epochs: 20, stage1_freeze: 10, stage2_epochs: 30
})

watch(() => props.datasets, (newDs) => {
  if (newDs && newDs.length > 0 && !selectedDataset.value) selectedDataset.value = newDs[0].id
}, { immediate: true })

const handleLaunch = async () => {
  isLaunching.value = true
  errorMsg.value = ''
  try {
    const modelArch = `${family.value}${scale.value}`
    const result = await launchTrainingJobAPI({
      job_id: `run_${modelArch}_${Date.now()}`,
      model_architecture: modelArch,
      task: task.value,
      dataset_id: selectedDataset.value,
      hyperparameters: params.value
    })
    emit('jobLaunched', result)
    if (typeof window !== 'undefined') window.location.hash = 'live-hud'
  } catch (err: any) {
    errorMsg.value = err.message || 'Launch error'
  } finally {
    isLaunching.value = false
  }
}
</script>

<template>
  <div class="view-container cockpit-container">
    <div class="cockpit-full-header">
      <h1 class="cockpit-main-title">TRAINING COCKPIT</h1>
      <p class="cockpit-main-subtitle">CONFIGURE ARCHITECTURE, HYPERPARAMETERS & INITIALIZE GPU TRAINING RUNS</p>
    </div>

    <div v-if="errorMsg" class="cyber-alert alert-critical" style="margin-bottom: 1rem;">
      <span>[ALERT] {{ errorMsg }}</span>
    </div>

    <div class="cockpit-quad-grid">
      <ArchitectureCard v-model:family="family" v-model:scale="scale" v-model:task="task" />
      <HyperparameterCard :params="params as any" @update:params="(p) => params = p as any" />
      <TwoStageControlCard :params="params" @update:params="(p) => params = p as any" />
      <HardwareEstimatorCard :datasets="datasets" v-model:selectedDataset="selectedDataset" :scale="scale" :batchSize="params.batch" :imgsz="params.imgsz" />
    </div>

    <div class="cockpit-bottom-bar">
      <button class="cockpit-launch-action-btn" :disabled="isLaunching" @click="handleLaunch">
        {{ isLaunching ? 'LAUNCHING...' : 'LAUNCH' }}
      </button>
    </div>
  </div>
</template>

// web/src/views/TrainingCockpit.jsx
import React, { useState } from 'react';
import ArchitectureCard from '../components/ArchitectureCard';
import HyperparameterCard from '../components/HyperparameterCard';
import TwoStageControlCard from '../components/TwoStageControlCard';
import HardwareEstimatorCard from '../components/HardwareEstimatorCard';
import { launchTrainingJobAPI } from '../api/client';

export default function TrainingCockpit({ datasets, onJobLaunched }) {
  const [family, setFamily] = useState('yolo26');
  const [scale, setScale] = useState('s');
  const [task, setTask] = useState('detect');
  const [selectedDataset, setSelectedDataset] = useState(datasets?.[0]?.dataset_id || 'frota_urbana_4classes');
  const [isLaunching, setIsLaunching] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [params, setParams] = useState({
    epochs: 50,
    batch_size: 16,
    imgsz: 640,
    optimizer: 'AdamW',
    lr0: 0.001,
    amp: true,
    two_stage: false,
    stage1_epochs: 20,
    stage1_freeze: 10,
    stage2_epochs: 30
  });

  React.useEffect(() => {
    if (datasets && datasets.length > 0 && (!selectedDataset || selectedDataset === 'coco8')) {
      setSelectedDataset(datasets[0].dataset_id);
    }
  }, [datasets, selectedDataset]);

  const handleLaunch = async () => {
    setIsLaunching(true);
    setErrorMsg('');
    try {
      const modelArch = `${family}${scale}`;
      const jobId = `run_${modelArch}_${Date.now()}`;
      const config = {
        job_id: jobId,
        model_architecture: modelArch,
        task: task,
        dataset_id: selectedDataset,
        hyperparameters: params
      };

      const result = await launchTrainingJobAPI(config);
      if (onJobLaunched) onJobLaunched(result);
      window.location.hash = 'live-hud';
    } catch (err) {
      setErrorMsg(err.message || 'Launch error');
    } finally {
      setIsLaunching(false);
    }
  };

  return (
    <div className="view-container cockpit-container">
      <div className="cockpit-full-header">
        <h1 className="cockpit-main-title">TRAINING COCKPIT</h1>
        <p className="cockpit-main-subtitle">
          CONFIGURE ARCHITECTURE, HYPERPARAMETERS & INITIALIZE GPU TRAINING RUNS
        </p>
      </div>

      {errorMsg && (
        <div className="cyber-alert alert-critical" style={{ marginBottom: '1rem' }}>
          <span>⚠️ {errorMsg}</span>
        </div>
      )}

      <div className="cockpit-quad-grid">
        <ArchitectureCard family={family} setFamily={setFamily} scale={scale} setScale={setScale} task={task} setTask={setTask} />
        <HyperparameterCard params={params} setParams={setParams} />
        <TwoStageControlCard params={params} setParams={setParams} />
        <HardwareEstimatorCard
          datasets={datasets}
          selectedDataset={selectedDataset}
          setSelectedDataset={setSelectedDataset}
          scale={scale}
          batchSize={params.batch_size}
          imgsz={params.imgsz}
        />
      </div>

      <div className="cockpit-bottom-bar">
        <button className="cockpit-launch-action-btn" onClick={handleLaunch} disabled={isLaunching}>
          {isLaunching ? 'LAUNCHING...' : 'LAUNCH'}
        </button>
      </div>
    </div>
  );
}
