// web/src/components/benchmarks/BenchmarkThroughputChart.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
  results?: any[]
}>(), {
  results: () => []
})

const valid = computed(() => props.results?.filter(r => r.status === 'SUCCESS') || [])
const maxFPS = computed(() => valid.value.length > 0 ? Math.max(...valid.value.map(r => r.fps), 100) : 100)

const getFillColor = (format: string) => {
  const f = format.toLowerCase()
  if (f.includes('tensorrt') || f.includes('engine')) return 'var(--cb-green)'
  if (f.includes('onnx')) return 'var(--cb-cyan)'
  return 'var(--cb-yellow)'
}
</script>

<template>
  <div class="cyber-card">
    <div class="card-header">
      <span class="card-title">THROUGHPUT COMPARISON (FPS)</span>
      <span class="badge-cyan">{{ valid.length > 0 ? 'REAL BENCHMARK DATA' : 'STANDBY' }}</span>
    </div>
    <div style="margin-top: 0.5rem;">
      <div v-if="valid.length === 0" style="text-align: center; padding: 2rem 1rem; color: #94a3b8; font-size: 0.8rem;">
        No benchmarks executed yet. Select runtime formats and execute the speed test.
      </div>
      <div
        v-for="(r, idx) in valid"
        v-else
        :key="idx"
        class="bar-chart-row"
      >
        <div class="bar-chart-label">{{ r.format }}</div>
        <div class="bar-chart-track">
          <div
            class="bar-chart-fill"
            :style="{
              width: `${Math.min(100, Math.max(6, (r.fps / maxFPS) * 100))}%`,
              background: getFillColor(r.format)
            }"
          />
        </div>
        <div class="bar-chart-val" :style="{ color: getFillColor(r.format) }">
          {{ r.fps?.toFixed(0) || 0 }} <span style="font-size: 0.65rem;">FPS</span>
        </div>
      </div>
    </div>
  </div>
</template>

// web/src/components/benchmarks/BenchmarkThroughputChart.jsx
import React from 'react';

export default function BenchmarkThroughputChart({ results = [] }) {
  const valid = results?.filter(r => r.status === 'SUCCESS') || [];
  const maxFPS = valid.length > 0 ? Math.max(...valid.map(r => r.fps), 100) : 100;

  return (
    <div className="cyber-card">
      <div className="card-header">
        <span className="card-title">THROUGHPUT COMPARISON (FPS)</span>
        <span className="badge-cyan">{valid.length > 0 ? 'REAL BENCHMARK DATA' : 'STANDBY'}</span>
      </div>
      <div style={{ marginTop: '0.5rem' }}>
        {valid.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '2rem 1rem', color: '#94a3b8', fontSize: '0.8rem' }}>
            No benchmarks executed yet. Select runtime formats and execute the speed test.
          </div>
        ) : (
          valid.map((r, idx) => {
            const pct = Math.min(100, Math.max(6, (r.fps / maxFPS) * 100));
            const isTensorRT = r.format?.toLowerCase().includes('tensorrt') || r.format?.toLowerCase().includes('engine');
            const isONNX = r.format?.toLowerCase().includes('onnx');

            let fillColor = 'var(--cb-yellow)';
            if (isTensorRT) fillColor = 'var(--cb-green)';
            else if (isONNX) fillColor = 'var(--cb-cyan)';

            return (
              <div key={idx} className="bar-chart-row">
                <div className="bar-chart-label">{r.format}</div>
                <div className="bar-chart-track">
                  <div className="bar-chart-fill" style={{ width: `${pct}%`, background: fillColor }} />
                </div>
                <div className="bar-chart-val" style={{ color: fillColor }}>
                  {r.fps?.toFixed(0) || 0} <span style={{ fontSize: '0.65rem' }}>FPS</span>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
