// web/src/components/modelzoo/ModelCardGrid.vue
<script setup lang="ts">
defineProps<{
  models: any[]
  selectedModel?: any
}>()

const emit = defineEmits<{
  (e: 'selectModel', m: any): void
}>()
</script>

<template>
  <div class="model-cards-grid">
    <div
      v-for="m in models"
      :key="m.id"
      class="model-item-card"
      :class="{ selected: selectedModel?.id === m.id }"
      @click="emit('selectModel', m)"
    >
      <div class="model-header-row">
        <span class="model-name">{{ m.name }}</span>
        <span class="model-task-badge">{{ m.task }}</span>
      </div>

      <div style="font-size: 0.72rem; color: #94a3b8; min-height: 32px;">
        {{ m.desc }}
      </div>

      <div class="model-stat-grid">
        <div class="model-stat-box">
          <div class="model-stat-val" style="color: var(--cb-green);">{{ m.map5095 }}%</div>
          <div class="model-stat-lbl">mAP 50-95</div>
        </div>
        <div class="model-stat-box">
          <div class="model-stat-val">{{ m.params }}M</div>
          <div class="model-stat-lbl">PARAMS</div>
        </div>
        <div class="model-stat-box">
          <div class="model-stat-val" style="color: var(--cb-yellow);">{{ m.trtLatency }}ms</div>
          <div class="model-stat-lbl">RTX 5090</div>
        </div>
      </div>
    </div>
  </div>
</template>

// web/src/components/modelzoo/ModelCardGrid.jsx
import React from 'react';

export default function ModelCardGrid({ models, selectedModel, onSelectModel }) {
  return (
    <div className="model-cards-grid">
      {models.map((m) => {
        const isSelected = selectedModel?.id === m.id;
        return (
          <div
            key={m.id}
            className={`model-item-card ${isSelected ? 'selected' : ''}`}
            onClick={() => onSelectModel(m)}
          >
            <div className="model-header-row">
              <span className="model-name">{m.name}</span>
              <span className="model-task-badge">{m.task}</span>
            </div>

            <div style={{ fontSize: '0.72rem', color: '#94a3b8', minHeight: '32px' }}>
              {m.desc}
            </div>

            <div className="model-stat-grid">
              <div className="model-stat-box">
                <div className="model-stat-val" style={{ color: 'var(--cb-green)' }}>{m.map5095}%</div>
                <div className="model-stat-lbl">mAP 50-95</div>
              </div>
              <div className="model-stat-box">
                <div className="model-stat-val">{m.params}M</div>
                <div className="model-stat-lbl">PARAMS</div>
              </div>
              <div className="model-stat-box">
                <div className="model-stat-val" style={{ color: 'var(--cb-yellow)' }}>{m.trtLatency}ms</div>
                <div className="model-stat-lbl">RTX 5090</div>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
