// web/src/components/datasets/ClassSnapshotModal.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { YOLO_CLASSES, decodeYoloClass } from './yolo_coco_classes'
import DatasetCyberIcons from './DatasetCyberIcons.vue'

const props = defineProps<{ isOpen: boolean; datasetId?: string; className?: string | null; currentTarget?: string }>()
const emit = defineEmits<{ (e: 'close'): void; (e: 'saveTarget', origClass: string, targetClass: string): void }>()

const target = ref(props.currentTarget || 'carro')
const search = ref('')
const sample = ref<any>(null)
const isLoading = ref(false)

const filtered = computed(() => YOLO_CLASSES.filter(c => c.label.toLowerCase().includes(search.value.toLowerCase()) || c.en.toLowerCase().includes(search.value.toLowerCase())))

const fetchSample = async () => {
  if (!props.datasetId || !props.className) return
  isLoading.value = true
  try {
    const res = await fetch(`/api/v1/training/datasets/sample?id=${props.datasetId}&class=${encodeURIComponent(props.className)}&t=${Date.now()}`)
    if (res.ok) sample.value = await res.json()
  } finally {
    isLoading.value = false
  }
}

watch(() => [props.isOpen, props.className, props.currentTarget], () => {
  if (props.isOpen && props.className) {
    target.value = props.currentTarget || 'carro'
    search.value = ''
    fetchSample()
  }
})

const bx = computed(() => sample.value?.bbox ? (sample.value.bbox[0] - sample.value.bbox[2] / 2) * 1000 : 0)
const by = computed(() => sample.value?.bbox ? (sample.value.bbox[1] - sample.value.bbox[3] / 2) * 1000 : 0)
const bw = computed(() => sample.value?.bbox ? sample.value.bbox[2] * 1000 : 0)
const bh = computed(() => sample.value?.bbox ? sample.value.bbox[3] * 1000 : 0)
</script>

<template>
  <div v-if="isOpen" class="modal-backdrop" @click="emit('close')">
    <div class="import-modal-box" style="max-width: 680px;" @click.stop>
      <div class="card-header" style="margin-bottom: 0.65rem;">
        <span class="card-title">SNAPSHOT: "{{ className }}" ({{ decodeYoloClass(className) }})</span>
        <button class="cyber-pill" style="padding: 0.2rem 0.5rem;" @click="emit('close')">✕</button>
      </div>

      <div style="display: grid; grid-template-columns: 1.2fr 1fr; gap: 0.85rem;">
        <div>
          <div style="width: 100%; height: 215px; background: #05070a; border: 1px solid rgba(0,240,255,0.3); border-radius: 4px; display: flex; align-items: center; justify-content: center; overflow: hidden;">
            <div v-if="isLoading" style="color: var(--cb-yellow); font-family: var(--font-mono); font-size: 0.75rem;">CARREGANDO...</div>
            <svg v-else-if="sample?.image_url" viewBox="0 0 1000 1000" preserveAspectRatio="xMidYMid meet" style="width: 100%; height: 100%; display: block;">
              <image :href="sample.image_url" x="0" y="0" width="1000" height="1000" preserveAspectRatio="none" />
              <template v-if="sample.bbox">
                <rect :x="bx" :y="by" :width="bw" :height="bh" fill="rgba(0, 240, 255, 0.2)" stroke="#00f0ff" stroke-width="8" />
                <text :x="bx + 10" :y="Math.max(by - 15, 35)" fill="#00f0ff" font-size="42" font-family="monospace" font-weight="bold">{{ className }}</text>
              </template>
            </svg>
            <div v-else style="color: #64748b; font-size: 0.75rem;">Sem preview.</div>
          </div>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 0.4rem; margin-top: 0.4rem;">
            <button class="cyber-action-btn secondary" style="padding: 0.45rem;" :disabled="isLoading" @click="fetchSample">NEXT</button>
            <button class="cyber-action-btn danger" style="padding: 0.45rem;" @click="() => { if (className) emit('saveTarget', className, 'ignorar'); emit('close'); }">IGNORE</button>
          </div>
        </div>

        <div style="display: flex; flex-direction: column; justify-content: space-between;">
          <div>
            <div class="selector-label" style="margin-bottom: 0.3rem;">ESCOLHA A CLASSE DESTINO:</div>
            <input type="text" placeholder="Filtrar classe..." :value="search" style="width: 100%; background: #05070a; border: 1px solid rgba(0,240,255,0.25); color: #fff; padding: 0.25rem 0.5rem; font-size: 0.7rem; border-radius: 3px; margin-bottom: 0.35rem; font-family: var(--font-mono);" @input="(e) => search = (e.target as HTMLInputElement).value" />
            <div style="height: 135px; overflow-y: auto; display: flex; flex-direction: column; gap: 0.25rem; padding-right: 3px;">
              <div v-for="c in filtered" :key="c.id" class="class-mapper-row" :style="{ cursor: 'pointer', height: '28px', padding: '0.2rem 0.5rem', borderColor: target === c.id ? 'var(--cb-yellow)' : 'rgba(0,240,255,0.15)', background: target === c.id ? 'rgba(252,238,10,0.15)' : 'rgba(0,0,0,0.4)' }" @click="target = c.id">
                <span :style="{ color: target === c.id ? 'var(--cb-yellow)' : '#fff', fontSize: '0.7rem', fontFamily: 'var(--font-mono)', fontWeight: target === c.id ? '700' : '400' }">{{ target === c.id ? '[X] ' : '[-] ' }}{{ c.label }} <span :style="{ color: target === c.id ? '#fef08a' : '#64748b', fontSize: '0.62rem' }">[{{ c.en }}]</span></span>
                <span v-if="target === c.id" class="badge-yellow" style="font-size: 0.55rem; padding: 0.05rem 0.3rem;">SELECTED</span>
              </div>
            </div>
          </div>
          <button class="cyber-action-btn" style="width: 100%; padding: 0.6rem; margin-top: 0.5rem;" @click="() => { if (className) emit('saveTarget', className, target); emit('close'); }">
            <DatasetCyberIcons name="launch" :size="14" color="#07080c" /><span>SALVAR</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// web/src/components/datasets/ClassSnapshotModal.jsx
import React, { useState, useEffect } from 'react';
import { YOLO_CLASSES, decodeYoloClass } from './yolo_coco_classes';
import DatasetCyberIcon from './DatasetCyberIcons';

export default function ClassSnapshotModal({ isOpen, onClose, datasetId, className, currentTarget, onSaveTarget }) {
  const [target, setTarget] = useState(currentTarget || 'carro');
  const [search, setSearch] = useState('');
  const [sample, setSample] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const filtered = YOLO_CLASSES.filter(c => c.label.toLowerCase().includes(search.toLowerCase()) || c.en.toLowerCase().includes(search.toLowerCase()));

  const fetchSample = async () => {
    if (!datasetId || !className) return;
    setIsLoading(true);
    try {
      const res = await fetch(`/api/v1/training/datasets/sample?id=${datasetId}&class=${encodeURIComponent(className)}&t=${Date.now()}`);
      if (res.ok) setSample(await res.json());
    } finally { setIsLoading(false); }
  };

  useEffect(() => {
    if (isOpen && className) {
      setTarget(currentTarget || 'carro');
      setSearch('');
      fetchSample();
    }
  }, [isOpen, className, currentTarget]);

  if (!isOpen) return null;

  const bx = sample?.bbox ? (sample.bbox[0] - sample.bbox[2] / 2) * 1000 : 0;
  const by = sample?.bbox ? (sample.bbox[1] - sample.bbox[3] / 2) * 1000 : 0;
  const bw = sample?.bbox ? sample.bbox[2] * 1000 : 0;
  const bh = sample?.bbox ? sample.bbox[3] * 1000 : 0;

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="import-modal-box" style={{ maxWidth: '680px' }} onClick={(e) => e.stopPropagation()}>
        <div className="card-header" style={{ marginBottom: '0.65rem' }}>
          <span className="card-title">SNAPSHOT: "{className}" ({decodeYoloClass(className)})</span>
          <button className="cyber-pill" style={{ padding: '0.2rem 0.5rem' }} onClick={onClose}>✕</button>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: '0.85rem' }}>
          <div>
            <div style={{ width: '100%', height: '215px', background: '#05070a', border: '1px solid rgba(0,240,255,0.3)', borderRadius: '4px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>
              {isLoading ? (
                <div style={{ color: 'var(--cb-yellow)', fontFamily: 'var(--font-mono)', fontSize: '0.75rem' }}>CARREGANDO...</div>
              ) : sample?.image_url ? (
                <svg viewBox="0 0 1000 1000" preserveAspectRatio="xMidYMid meet" style={{ width: '100%', height: '100%', display: 'block' }}>
                  <image href={sample.image_url} x="0" y="0" width="1000" height="1000" preserveAspectRatio="none" />
                  {sample.bbox && (
                    <>
                      <rect x={bx} y={by} width={bw} height={bh} fill="rgba(0, 240, 255, 0.2)" stroke="#00f0ff" strokeWidth="8" />
                      <text x={bx + 10} y={Math.max(by - 15, 35)} fill="#00f0ff" fontSize="42" fontFamily="monospace" fontWeight="bold">{className}</text>
                    </>
                  )}
                </svg>
              ) : <div style={{ color: '#64748b', fontSize: '0.75rem' }}>Sem preview.</div>}
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.4rem', marginTop: '0.4rem' }}>
              <button className="cyber-action-btn secondary" style={{ padding: '0.45rem' }} onClick={fetchSample} disabled={isLoading}>NEXT</button>
              <button className="cyber-action-btn danger" style={{ padding: '0.45rem' }} onClick={() => { onSaveTarget(className, 'ignorar'); onClose(); }}>IGNORE</button>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
            <div>
              <div className="selector-label" style={{ marginBottom: '0.3rem' }}>ESCOLHA A CLASSE DESTINO:</div>
              <input type="text" placeholder="🔍 Filtrar..." value={search} onChange={e => setSearch(e.target.value)} style={{ width: '100%', background: '#05070a', border: '1px solid rgba(0,240,255,0.25)', color: '#fff', padding: '0.25rem 0.5rem', fontSize: '0.7rem', borderRadius: '3px', marginBottom: '0.35rem', fontFamily: 'var(--font-mono)' }} />
              <div style={{ height: '135px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.25rem', paddingRight: '3px' }}>
                {filtered.map(c => {
                  const isSel = target === c.id;
                  return (
                    <div key={c.id} className="class-mapper-row" style={{ cursor: 'pointer', height: '28px', padding: '0.2rem 0.5rem', borderColor: isSel ? 'var(--cb-yellow)' : 'rgba(0,240,255,0.15)', background: isSel ? 'rgba(252,238,10,0.15)' : 'rgba(0,0,0,0.4)' }} onClick={() => setTarget(c.id)}>
                      <span style={{ color: isSel ? 'var(--cb-yellow)' : '#fff', fontSize: '0.7rem', fontFamily: 'var(--font-mono)', fontWeight: isSel ? '700' : '400' }}>
                        {isSel ? '✓ ' : '◇ '}{c.label} <span style={{ color: isSel ? '#fef08a' : '#64748b', fontSize: '0.62rem' }}>[{c.en}]</span>
                      </span>
                      {isSel && <span className="badge-yellow" style={{ fontSize: '0.55rem', padding: '0.05rem 0.3rem' }}>SELECTED</span>}
                    </div>
                  );
                })}
              </div>
            </div>

            <button className="cyber-action-btn" style={{ width: '100%', padding: '0.6rem', marginTop: '0.5rem' }} onClick={() => { onSaveTarget(className, target); onClose(); }}>
              <DatasetCyberIcon name="launch" size={14} color="#07080c" />
              <span>SAVE</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
