// web/src/App.jsx
import React, { useState, useEffect } from 'react';
import TopCyberNav from './components/TopCyberNav';
import TrainingCockpit from './views/TrainingCockpit';
import LiveHudStudio from './views/LiveHudStudio';
import BenchmarkStudio from './views/BenchmarkStudio';
import PlaygroundStudio from './views/PlaygroundStudio';
import DatasetStudio from './views/DatasetStudio';
import ModelZooStudio from './views/ModelZooStudio';
import { fetchTelemetryAPI, fetchDatasetsAPI } from './api/client';

export default function App() {
  const getInitialTab = () => {
    const hash = window.location.hash.replace('#', '');
    return hash || 'cockpit';
  };

  const [activeTab, setActiveTab] = useState(getInitialTab);
  const [telemetry, setTelemetry] = useState(null);
  const [datasets, setDatasets] = useState([]);

  useEffect(() => {
    const handleHashChange = () => {
      const hash = window.location.hash.replace('#', '');
      setActiveTab(hash || 'cockpit');
    };
    window.addEventListener('hashchange', handleHashChange);
    return () => window.removeEventListener('hashchange', handleHashChange);
  }, []);

  const navigateTo = (tabId) => {
    window.location.hash = tabId;
    setActiveTab(tabId);
  };

  useEffect(() => {
    const loadInitialData = async () => {
      const tel = await fetchTelemetryAPI();
      if (tel) setTelemetry(tel);
      const ds = await fetchDatasetsAPI();
      if (ds) setDatasets(ds);
    };
    loadInitialData();
    const interval = setInterval(loadInitialData, 3000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="app-layout" style={{ flexDirection: 'column' }}>
      <TopCyberNav activeTab={activeTab} onSelectTab={navigateTo} gpuStats={telemetry?.gpu_stats} />
      <main className="content-body">
        {activeTab === 'cockpit' && (
          <TrainingCockpit datasets={datasets} onJobLaunched={() => navigateTo('live-hud')} />
        )}
        {activeTab === 'live-hud' && <LiveHudStudio />}
        {activeTab === 'benchmarks' && <BenchmarkStudio />}
        {activeTab === 'datasets' && <DatasetStudio datasets={datasets} />}
        {activeTab === 'playground' && <PlaygroundStudio />}
        {activeTab === 'model-zoo' && <ModelZooStudio />}
      </main>
    </div>
  );
}

// web/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import TopCyberNav from './components/TopCyberNav.vue'
import TrainingCockpit from './views/TrainingCockpit.vue'
import LiveHudStudio from './views/LiveHudStudio.vue'
import BenchmarkStudio from './views/BenchmarkStudio.vue'
import PlaygroundStudio from './views/PlaygroundStudio.vue'
import DatasetStudio from './views/DatasetStudio.vue'
import ModelZooStudio from './views/ModelZooStudio.vue'
import { fetchTelemetryAPI, fetchDatasetsAPI } from './api/client'
import type { TelemetryData } from './types/telemetry'
import type { DatasetInfo } from './types/dataset'

const getInitialTab = () => {
  const hash = window.location.hash.replace('#', '')
  return hash || 'cockpit'
}

const activeTab = ref(getInitialTab())
const telemetry = ref<TelemetryData | null>(null)
const datasets = ref<DatasetInfo[]>([])
let pollTimer: any = null

const handleHashChange = () => {
  const hash = window.location.hash.replace('#', '')
  activeTab.value = hash || 'cockpit'
}

const navigateTo = (tabId: string) => {
  window.location.hash = tabId
  activeTab.value = tabId
}

const loadInitialData = async () => {
  const tel = await fetchTelemetryAPI()
  if (tel) telemetry.value = tel
  const ds = await fetchDatasetsAPI()
  if (ds) datasets.value = ds
}

onMounted(() => {
  window.addEventListener('hashchange', handleHashChange)
  loadInitialData()
  pollTimer = setInterval(loadInitialData, 3000)
})

onUnmounted(() => {
  window.removeEventListener('hashchange', handleHashChange)
  if (pollTimer) clearInterval(pollTimer)
})
</script>

<template>
  <div class="app-layout" style="flex-direction: column;">
    <TopCyberNav
      :activeTab="activeTab"
      :gpuStats="telemetry?.gpu_stats"
      @selectTab="navigateTo"
    />
    <main class="content-body">
      <TrainingCockpit
        v-if="activeTab === 'cockpit'"
        :datasets="datasets"
        @jobLaunched="() => navigateTo('live-hud')"
      />
      <LiveHudStudio v-else-if="activeTab === 'live-hud'" />
      <BenchmarkStudio v-else-if="activeTab === 'benchmarks'" />
      <DatasetStudio v-else-if="activeTab === 'datasets'" :datasets="datasets" />
      <PlaygroundStudio v-else-if="activeTab === 'playground'" />
      <ModelZooStudio v-else-if="activeTab === 'model-zoo'" />
    </main>
  </div>
</template>
